/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.scientiamobile.wurfl.wmclient.kotlin

class WmClient {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
