/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.scientiamobile.wurfl.wmclient.kotlin

import kotlin.test.Test
import kotlin.test.assertTrue

class WmClientTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = WmClient()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
